### ISSUE TITLE
Release weights

### ISSUE THREAD

**Issue by araujoalexandre** [berndprach/1LipschitzLayersCompared#4]
Hi ! 

Would it be possible to release the weights of the models you have trained?

Thank you

**Comment by fabiobrau** [comment]
Hi, yes of course. We will upload them (or a subset) in the next few days.

Thanks for your interest!

**Comment by fabiobrau** [comment]
Hi @araujoalexandre ,

Due to space limits, we uploaded the 24-hour training for the CIFAR10 dataset only for the XS,S, and M models. The runs are stored in a directory tree like the one described in the README.

### Related to the Lipschtiz of SOC [Issue](https://github.com/berndprach/1LipschitzLayersCompared/issues/1)
If you want to check the lip constant of each model, you can find the estimated value at the very end of each training.log file. 
The following bash command gives you a summary
```[bash]
find . -type f -name "training.log" -printf '%p /' -exec tail -n 1 {} \; | cut -d "/" -f 2,3,6 | column -t
```
run it from the unpacked directory.
